export { default as GauthLogo } from './GauthLogo';
export { default as GKRLogo } from './GKRLogo';
export { default as Folder } from './Folder'
export { default as Profile } from './Profile';
export { default as Handshake } from './HandShake';
export { default as Bell } from './Bell';
export { default as Exit } from "./Exit";
export { default as GKRLogoA } from './GKRLogoA';
export { default as Document } from './Document';
export { default as Cution } from './Cution';
export { default as Letter } from './Letter';
export { default as Addfile } from './Addfile';
export { default as Magnifier } from './Magnifier';
export { default as Calendar } from './Calendar';
export { default as Box } from './Box'
export { default as People } from './People'
export { default as Logo2 } from './Logo2'
export { default as Logo2A } from 'asset/svg/Logo2A'
